### ISSUE TITLE
Extract all package data from HTML 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#12]
- [x] String name;
- [x]  String author;
- [x]  List<String> uploaders;
- [x]  List<Version> versions;  up to the first 10
- [x]  String url;
- [x]  String version_url;
 - [x] Latest version; 
- [x] score 
_____________________
### Deprecated fields. 
_These fields no longer appear on pub.dev_

~~DateTime created;~~
~~int downloads;~~

**Comment by GroovinChip** [comment]
Are we able to get the score this way?

**Comment by ThinkDigitalSoftware** [comment]
Yes, definitely. "Everything the light touches" we can grab. Scraping
downloads the entire page, word for work ( element for element) and allows
me to extract whatever the heck I want

**Comment by ThinkDigitalSoftware** [comment]
@GroovinChip We're currently supporting the following variables in the fork of the pub_client package I'm working on. There's more that can be grabbed. For instance, the readme. What do you feel we need to add to this list?
```dart
FullPackage(
      {@required this.name,
      @required this.url,
      @required this.author,
      this.uploaders,
      this.versions,
      this.latestVersion,
      this.score,
      this.description,
      this.dateCreated,
      this.dateModified,
      this.compatibilityTags});
```
