### ISSUE TITLE
App Bar should be pinned. 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#13]
For the main screen, it should always say Dart packages at the top. The search bar should disappear when scrolling since a user won't need to search while reading the rest of the info for the package.
We can also add the behavior where onscroll up start, the search bar can animate in and float over the window and then on upward drag end, a timer can be started to make the search bar disappear. Does that sound like too much?

**Comment by GroovinChip** [comment]
I can pin the appBar not sure if I can do the animation you describe. Will look into it.

**Comment by ThinkDigitalSoftware** [comment]
Well later for that then
