### ISSUE TITLE
Future from getPageOfPackages does not return in release mode on Android

### ISSUE THREAD

**Issue by GroovinChip** [ThinkDigitalSoftware/tavern#18]
Steps to reproduce:
- Run the app in release mode (with my latest commits)
OR
- `flutter build apk --release` and `flutter install` and launch the app

**Comment by ThinkDigitalSoftware** [comment]
I've had issues getting this to run as well in debug mode

**Comment by GroovinChip** [comment]
I will add some code to deal with this maybe tonight or tomorrow. It's not a solution to the future, but I can at least account for errors
