### ISSUE TITLE
Fix focus on search text box

### ISSUE THREAD

**Issue by GroovinChip** [ThinkDigitalSoftware/tavern#29]
When the user taps on the search bar on the packages feed, and taken to the search screen, the keyboard flashes for a moment and disappears. The focus on the search field should be constant unless the user unfocuses it.

**Comment by ThinkDigitalSoftware** [comment]
@GroovinChip for some reason, the automaticallyFocus feature doesn't work with our current uses. I tried to make it focus manually and it works, but throws an error. I haven't figured out the solution for this yet

**Comment by ThinkDigitalSoftware** [comment]
This is what #22 is about
