### ISSUE TITLE
Actual search (using the button) doesn't work yet

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#38]
If you hit search, it should show a page with the search results. The suggestion list can show a few suggestions based on maybe 5 package names, but the rest, the user should hit search and see a page full of results

**Comment by GroovinChip** [comment]
Even if the search query is empty? Just hit the button and go?

**Comment by ThinkDigitalSoftware** [comment]
Oh, not if it's empty. But if there's a query, we should allow the user to search for it. The suggestions box won't always have everything and even if you check google, they only show a few top results in the suggestions and the rest are left for the search results. Also, we need a "no results found" screen

**Comment by ThinkDigitalSoftware** [comment]
closed in 90baaf23b1c0549821cb015112c7b464ab1926b4
