### ISSUE TITLE
Fix html characters showing up in code blocks

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#41]
Example:  In cameras, in the description, it shows `&lt` instead of `<`

**Comment by Ayman-Barghout** [comment]
Is this issue still open?
I viewed the project on Android Emulator and I didn't get any HTML characters, is there anything I am missing or is this issue fixed?

**Comment by ThinkDigitalSoftware** [comment]
Good question. Did you check the cameras package?

**Comment by ThinkDigitalSoftware** [comment]
Nope. This is no longer an issue. Thanks for checking in on that!
