### ISSUE TITLE
Package details don't load

### ISSUE THREAD

**Issue by 8bitgentleman** [ThinkDigitalSoftware/tavern#47]
Hey this is a great idea for an app, I've been wanting something like this for a while. I've got some issues with the 1.01 release though. When I click into a package I just get the circle loading animation and it never actually loads the package details. 
Thanks!

**Comment by ThinkDigitalSoftware** [comment]
Thank you for opening an issue! This should be fixed now in 21734c6.
[v1.2.0](https://github.com/ThinkDigitalSoftware/tavern/releases/tag/v1.2.0) is now available for download in the releases section
