### ISSUE TITLE
Recently Updated subscription

### ISSUE THREAD

**Issue by GroovinChip** [ThinkDigitalSoftware/tavern#5]
Besides for the New Packages subscription, we should also support subscribing to the Recently Updated feed

**Comment by ThinkDigitalSoftware** [comment]
Yes, definitely.

**Comment by ThinkDigitalSoftware** [comment]
Do you have a link to this feed? I don't see it on pub.dev

**Comment by ThinkDigitalSoftware** [comment]
I found it with HTTP. Looking for an API or ATOM link

**Comment by ThinkDigitalSoftware** [comment]
oh, it's THE atom link, lol. https://pub.dev/feed.atom

**Comment by ThinkDigitalSoftware** [comment]
Added
