### ISSUE TITLE
Determine UI for switching between 'Flutter', 'Web', and 'All' per pub main UI

### ISSUE THREAD

**Issue by GroovinChip** [ThinkDigitalSoftware/tavern#6]
![chrome_LdiTlOBZLH](https://user-images.githubusercontent.com/4250470/59238220-1779f000-8bcb-11e9-9445-b751a3fe3d1f.png)

**Comment by ThinkDigitalSoftware** [comment]
How often to you expect these to be used? That'll help determine how prominent they should be. We could make them top level, but I feel personally that these are less used as a common feature and more like a setting. What say you?

**Comment by GroovinChip** [comment]
Personally, I only ever use the Flutter tab. I just thought that since you want as much feature parity as possible that we should include it somehow.

**Comment by ThinkDigitalSoftware** [comment]
Agreed, but how prominent should it be?

**Comment by GroovinChip** [comment]
Perhaps a PopupMenuButton on the AppBar?

**Comment by ThinkDigitalSoftware** [comment]
Or a `DropdownMenuButton`. That way the selected option can be visible.

**Comment by GroovinChip** [comment]
I'll come up with something
