### ISSUE TITLE
Add links to publisher

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#62]

**Comment by mcbaloo** [comment]
can I ask what link you're looking to add to the dependencies and publisher? I can work on that.

**Comment by ThinkDigitalSoftware** [comment]
@mcbaloo hey, thanks for contributing! What I'm looking for is when you tap the name of the publisher, it does a search for packages  by publisher. I want to duplicate the pub.dev functionality when a publisher is tapped.
For the dependencies, when you tap one, it should take you to the package details page for that package

**Comment by mcbaloo** [comment]
Okay. I understand you well. I would look into it.

**Comment by mcbaloo** [comment]
@ThinkDigitalSoftware 
 you're referring to clicking on the publisher name as included in the image right? Asking for clarity. 

![changes](https://user-images.githubusercontent.com/20352841/84310499-08bd7480-ab62-11ea-8a68-dabfd8c2f1d7.PNG)

**Comment by ThinkDigitalSoftware** [comment]
@mcbaloo Yes, correct

**Comment by mcbaloo** [comment]
I think this is closed now right?

**Comment by ThinkDigitalSoftware** [comment]
Yes, let me separate it into 2 issues and close it
