### ISSUE TITLE
Latest version shows popup menu in weird spot

### ISSUE THREAD

**Issue by GroovinChip** [ThinkDigitalSoftware/tavern#63]
http://imgur.com/gallery/QUgmr5G

Samsung S10+, Android 10

**Comment by ThinkDigitalSoftware** [comment]
Thank you for checking this out. I actually didn't bother testing this version on mobile. I think that modification was made to allow it to fit in with our notched brethren. I wish there was a safe range to allow this to popup, since with  notches, the top of the menu gets cut off

**Comment by GroovinChip** [comment]
I haven't looked at the source code in a long time, but I assume you are using `showMenu` to show the popup. You can use the offset property to determine where the popup shows.

**Comment by ThinkDigitalSoftware** [comment]
Yeah, that's what I'm doing. That's why it's in this position.  I believe I recently moved this widget to a new location and forgot to update the offset.

**Comment by GroovinChip** [comment]
You could probably use LayoutBuilder to determine which offsets to use
