### ISSUE TITLE
Fix AutoSizeText so that longer publisher names show up

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#68]
To reproduce:
Search for rxdart, click the publisher link in the About tab.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-23 at 14 57 24](https://user-images.githubusercontent.com/23037821/85468959-ed8b3580-b561-11ea-92c8-e14f9fadebfc.png)

**Comment by mcbaloo** [comment]
looking into this
