### ISSUE TITLE
Set up CI/CD with Codemagic

### ISSUE THREAD

**Issue by GroovinChip** [ThinkDigitalSoftware/tavern#7]
Have it target master, so any approved merges result in a release apk sent to developers. That way we can be up to date on the progress.

**Comment by ThinkDigitalSoftware** [comment]
This would be awesome. I don't have any experience with CodeMagic yet. Do you? or @felangel?

**Comment by GroovinChip** [comment]
I do, but I think you have to set it up since you own the repo. It's tied to your GitHub account. It's very easy to set up.

**Comment by ThinkDigitalSoftware** [comment]
On it

**Comment by ThinkDigitalSoftware** [comment]
Wow, that was the EASIEST thing I've ever done! It was a 2 step process. Sign in and select your project  and it starts building!

**Comment by GroovinChip** [comment]
Nice!

**Comment by ThinkDigitalSoftware** [comment]
Done
