### ISSUE TITLE
Add proper versioning 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ThinkDigitalSoftware/tavern#8]
I forgot to check and set this. I'm horrible with versioning. 
Any tools or git hooks that will check for a version bump for each push?

**Comment by GroovinChip** [comment]
You just want to check for a version bump automatically, or you want to actually bump the version automatically on push?

**Comment by ThinkDigitalSoftware** [comment]
Check. Just in case I'm amending

**Comment by GroovinChip** [comment]
You can probably add a custom script to Codemagic that will do that
